
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - ::1

logger:
  default: info
  logs:
    homeassistant.components.command_line: debug

command_line:
  - sensor:
      unique_id: hourly_assistant
      name: Hourly Assistant
      command: >
        /opt/llamafile/google_gemma-3-4b-it-Q6_K.llamafile --cli --no-display-prompt -p "Please tell me a beautiful little story of maximum 50 words. There is a strict limit, so the story must be under 50 words. Thank you."
      command_timeout: 90
      scan_interval: 3600
